<div class="theme-default">
<div id="<?=$this->options["name"];?>" class="nivoSlider">
<?php
foreach ($this->entity as $item){
    $url=trim($item->getUrl());
    if (!empty($url)){
        $a_start="<a href=\"{$url}\" target=\"_blank\"  rel=\"nofollow\">";
        $a_end="</a>";
    } else {
        $a_start="";
        $a_end="";
    }
?>
    <?=$a_start;?>
       <img src="<?=$this->ImageStorage($this->options["category"],$item->getId(),"img");?>"  alt="<?=$this->escapeHtmlAttr($item->getAlt());?>" title="<?=$this->escapeHtmlAttr($item->getAlt());?>" />
    <?=$a_end;?>
<?php
}
    ?>
</div>
</div>