<?php
$this->headTitle($this->page->GetTitle());
$this->headMeta()->appendName('keywords', $this->page->GetKeywords());
$this->headMeta()->appendName('description', $this->page->GetDescription() );


echo $this->page->GetInfo();
//передать в макет имя локали, для мультиязычных сайтов
$this->layout()->locale=$this->page->Getlocale();

if ($this->getHelperPluginManager()->has("SearchIndex")){
    //поисковый индекс, если есть поисковый плагин-индексатор
    $this->SearchIndex(
        $this->page->GetInfo(),
        $this->page->GetTitle(),
        $this->url("slider",["link"=>$this->page->getLink()]),
        ["material_type"=>"","date_public"=>""]
    );
}
