<?php
$escape=new Zend\Escaper\Escaper("utf-8");
?>
   <div class="carousel-inner">
<?php
foreach ($this->entity as $k=>$item){
    $url=trim($item->getUrl());
    $active="";
    if (empty($k)){
        $active="active";
    }
    if (!empty($url)){
        $a_start="<a href=\"{$url}\" class=\"carousel-item {$active}\">";
        $a_end="</a>";
    } else {
        $a_start="<div class=\"carousel-item {$active}\">";
        $a_end="</div>";
    }
?>
    <?=$a_start;?> 
       <img src="<?=$this->ImageStorage($this->options["category"],$item->getId(),"img");?>" class="d-block mx-auto" alt="" title="<?=$escape->escapeHtmlAttr($item->getAlt());?>" />
       <?=$a_end;?>
<?php
}
    ?>
    </div>
